In [ ]:
import pandas as pd

df = pd.read_csv('WorldCups.csv', sep=",")
df

In [4]:
df.shape

(20, 10)

In [5]:
df.describe()

              Year  GoalsScored  QualifiedTeams  MatchesPlayed
count    20.000000    20.000000       20.000000      20.000000
mean   1974.800000   118.950000       21.250000      41.800000
std      25.582889    32.972836        7.268352      17.218717
min    1930.000000    70.000000       13.000000      17.000000
25%    1957.000000    89.000000       16.000000      30.500000
50%    1976.000000   120.500000       16.000000      38.000000
75%    1995.000000   145.250000       26.000000      55.000000
max    2014.000000   171.000000       32.000000      64.000000

In [6]:
df.head(2)

,Year,Country,Winner,Runners-Up,Third,Fourth,GoalsScored,QualifiedTeams,MatchesPlayed,Attendance
0,1930,Uruguay,Uruguay,Argentina,USA,Yugoslavia,70,13,18,590.549
1,1934,Italy,Italy,Czechoslovakia,Germany,Austria,70,16,17,363.000

In [7]:
df = df.rename(columns={'Year':'Ano','Country':'País','Winner':'Campeão','Runners-Up': 'Vice-Campeão','Third':'Terceiro','Fourth':'Quarto', 'GoalsScored':"Gols Marcados", 'QualifiedTeams':'Equipes Qualificads', 'MatchesPlayed':'Partidas Jogadas','Attendance':'Publico' })
df.head()

,Ano,País,Campeão,Vice-Campeão,Terceiro,Quarto,Gols Marcados,Equipes Qualificads,Partidas Jogadas,Publico
0,1930,Uruguay,Uruguay,Argentina,USA,Yugoslavia,70,13,18,590.549
1,1934,Italy,Italy,Czechoslovakia,Germany,Austria,70,16,17,363.000
2,1938,France,Italy,Hungary,Brazil,Sweden,84,15,18,375.700
3,1950,Brazil,Uruguay,Brazil,Sweden,Spain,88,13,22,1.045.246
4,1954,Switzerland,Germany FR,Hungary,Austria,Uruguay,140,16,26,768.607

In [8]:
df.loc[0:5, ['Ano', 'País','Campeão', 'Publico']]

    Ano         País     Campeão    Publico
0  1930      Uruguay     Uruguay    590.549
1  1934        Italy       Italy    363.000
2  1938       France       Italy    375.700
3  1950       Brazil     Uruguay  1.045.246
4  1954  Switzerland  Germany FR    768.607
5  1958       Sweden      Brazil    819.810

In [9]:
# QUANTIDADE DE VEZES QUE UM PAÍS FOI CAMPEÃO
df.value_counts(['Campeão'])

Campeão
Brazil        5
Italy         4
Germany FR    3
Argentina     2
Uruguay       2
England       1
France        1
Germany       1
Spain         1
dtype: int64

In [10]:
# Quais copas o brasil foi campeão
df.loc[df['Campeão']=='Brazil']

,Ano,País,Campeão,Vice-Campeão,Terceiro,Quarto,Gols Marcados,Equipes Qualificads,Partidas Jogadas,Publico
5,1958,Sweden,Brazil,Sweden,France,Germany FR,126,16,35,819.810
6,1962,Chile,Brazil,Czechoslovakia,Chile,Yugoslavia,89,16,32,893.172
8,1970,Mexico,Brazil,Italy,Germany FR,Uruguay,95,16,32,1.603.975
14,1994,USA,Brazil,Italy,Sweden,Bulgaria,141,24,52,3.587.538
16,2002,Korea/Japan,Brazil,Germany,Turkey,Korea Republic,161,32,64,2.705.197

In [11]:
# QUANTAS VEZES O BRASIL FOI VICE-CAMPEÃO
df.value_counts(['Vice-Campeão'])['Brazil']

2

In [12]:
# Quais os anos o Brasil foi Vice-Campeão
df.loc[df['Vice-Campeão']=='Brazil']

,Ano,País,Campeão,Vice-Campeão,Terceiro,Quarto,Gols Marcados,Equipes Qualificads,Partidas Jogadas,Publico
3,1950,Brazil,Uruguay,Brazil,Sweden,Spain,88,13,22,1.045.246
15,1998,France,France,Brazil,Croatia,Netherlands,171,32,64,2.785.100

In [13]:
import pandas as pd

df1 = pd.read_csv('worldCupPlayers.csv', sep=',')
df1.head()

,RoundID,MatchID,Team Initials,Coach Name,Line-up,Shirt Number,Player Name,Position,Event
0,201,1096,FRA,CAUDRON Raoul (FRA),S,0,Alex THEPOT,GK,NaN
1,201,1096,MEX,LUQUE Juan (MEX),S,0,Oscar BONFIGLIO,GK,NaN
2,201,1096,FRA,CAUDRON Raoul (FRA),S,0,Marcel LANGILLER,NaN,G40'
3,201,1096,MEX,LUQUE Juan (MEX),S,0,Juan CARRENO,NaN,G70'
4,201,1096,FRA,CAUDRON Raoul (FRA),S,0,Ernest LIBERATI,NaN,NaN

In [14]:
df1 = df1.rename(columns={'RoundID':'Id Rodada', 'MatchID':'Id Corresp', 'Team Initials':'Inciais Equipe','Coach Name':'Treinador', 'Line-up':'Alinhar', 'Shirt Number':'Número Camisa','Player Name':'Nome Jogador', 'Position':'Posição','Event':'Evento'})
df1.head(2)

,Id Rodada,Id Corresp,Inciais Equipe,Treinador,Alinhar,Número Camisa,Nome Jogador,Posição,Evento
0,201,1096,FRA,CAUDRON Raoul (FRA),S,0,Alex THEPOT,GK,NaN
1,201,1096,MEX,LUQUE Juan (MEX),S,0,Oscar BONFIGLIO,GK,NaN

In [15]:
import pandas as pd
df2 = pd.read_csv('WorldCupMatches.csv')
df2.head(3)

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
0,1930.0,13 Jul 1930 - 15:00,Group 1,Pocitos,Montevideo,France,4.0,1.0,Mexico,,4444.0,3.0,0.0,LOMBARDI Domingo (URU),CRISTOPHE Henry (BEL),REGO Gilberto (BRA),201.0,1096.0,FRA,MEX
1,1930.0,13 Jul 1930 - 15:00,Group 4,Parque Central,Montevideo,USA,3.0,0.0,Belgium,,18346.0,2.0,0.0,MACIAS Jose (ARG),MATEUCCI Francisco (URU),WARNKEN Alberto (CHI),201.0,1090.0,USA,BEL
2,1930.0,14 Jul 1930 - 12:45,Group 2,Parque Central,Montevideo,Yugoslavia,2.0,1.0,Brazil,,24059.0,2.0,0.0,TEJADA Anibal (URU),VALLARINO Ricardo (URU),BALWAY Thomas (FRA),201.0,1093.0,YUG,BRA

In [16]:
df2 = df2.rename(columns={'Year':'Ano', 'Datetime':'Data Hora', 'Stage':'Grupo','Stadium':'Estádio', 'City':'Cidade', 'Home Team Name':'Equipe da Casa','Home Team Goals':'Gols Equipe Casa', 'Away Team Goals':'GolsVisitante','Away Team Name':'Equipe Visitante','Attendance':'Publico','Referee':'Juiz'})
df2.head(2)

,Ano,Data Hora,Grupo,Estádio,Cidade,Equipe da Casa,Gols Equipe Casa,GolsVisitante,Equipe Visitante,Win conditions,Publico,Half-time Home Goals,Half-time Away Goals,Juiz,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
0,1930.0,13 Jul 1930 - 15:00,Group 1,Pocitos,Montevideo,France,4.0,1.0,Mexico,,4444.0,3.0,0.0,LOMBARDI Domingo (URU),CRISTOPHE Henry (BEL),REGO Gilberto (BRA),201.0,1096.0,FRA,MEX
1,1930.0,13 Jul 1930 - 15:00,Group 4,Parque Central,Montevideo,USA,3.0,0.0,Belgium,,18346.0,2.0,0.0,MACIAS Jose (ARG),MATEUCCI Francisco (URU),WARNKEN Alberto (CHI),201.0,1090.0,USA,BEL

In [17]:
# Maior publico em cada grupo de todas as copas.
df2.groupby(['Grupo']).apply(lambda df2: df2.loc[df2.Publico.idxmax()])

,Ano,Data Hora,Grupo,Estádio,Cidade,Equipe da Casa,Gols Equipe Casa,GolsVisitante,Equipe Visitante,Win conditions,Publico,Half-time Home Goals,Half-time Away Goals,Juiz,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
Grupo,,,,,,,,,,,,,,,,,,,,
Final,1986.0,29 Jun 1986 - 12:00,Final,Estadio Azteca,Mexico City,Argentina,3.0,2.0,Germany FR,,114600.0,1.0,0.0,ARPPI FILHO Romualdo (BRA),FREDRIKSSON Erik (SWE),ULLOA MORERA Berny (CRC),3467.0,393.0,ARG,FRG
First round,1938.0,05 Jun 1938 - 17:00,First round,Stade Olympique,Colombes,France,3.0,1.0,Belgium,,30454.0,2.0,1.0,WUETHRICH Hans (SUI),KRIST Gustav (TCH),BIRLEM Alfred (GER),206.0,1146.0,FRA,BEL
Group 1,1950.0,01 Jul 1950 - 15:00,Group 1,Maracan� - Est�dio Jornalista M�rio Filho,Rio De Janeiro,Brazil,2.0,0.0,Yugoslavia,,142429.0,1.0,0.0,GRIFFITHS Benjamin (WAL),BERANEK Alois (AUT),DA COSTA VIEIRA Jose (POR),208.0,1191.0,BRA,YUG
Group 2,1982.0,02 Jul 1982 - 21:00,Group 2,Santiago Bernabeu,Madrid,Germany FR,2.0,1.0,Spain,,90089.0,0.0,0.0,CASARIN Paolo (ITA),WOEHRER Franz (AUT),PALOTAI Karoly (HUN),294.0,900.0,FRG,ESP
Group 3,1982.0,13 Jun 1982 - 20:00,Group 3,Camp Nou,Barcelona,Argentina,0.0,1.0,Belgium,,95000.0,0.0,0.0,CHRISTOV Vojtech (TCH),PALOTAI Karoly (HUN),JARGUZ Alojzy (POL),293.0,749.0,ARG,BEL
Group 4,1974.0,19 Jun 1974 - 19:30,Group 4,Neckarstadion,Stuttgart,Argentina,1.0,1.0,Italy,,70100.0,1.0,1.0,KAZAKOV Pavel (URS),GLOECKNER Rudolf (GDR),RAINEA Nicolae (ROU),262.0,1949.0,ARG,ITA
Group 5,1982.0,16 Jun 1982 - 21:00,Group 5,Luis Casanova,Valencia,Spain,1.0,1.0,Honduras,,49562.0,0.0,1.0,ITHURRALDE Arturo Andres (ARG),DOTCHEV Bogdan (BUL),BARRANCOS Luis (BOL),293.0,901.0,ESP,HON
Group 6,1950.0,16 Jul 1950 - 15:00,Group 6,Maracan� - Est�dio Jornalista M�rio Filho,Rio De Janeiro,Uruguay,2.0,1.0,Brazil,,173850.0,0.0,0.0,READER George (ENG),ELLIS Arthur (ENG),MITCHELL George (SCO),209.0,1190.0,URU,BRA
Group A,1986.0,31 May 1986 - 12:00,Group A,Estadio Azteca,Mexico City,Bulgaria,1.0,1.0,Italy,,96000.0,0.0,1.0,FREDRIKSSON Erik (SWE),CODESAL MENDEZ Edgardo (MEX),ROTH Volker (GER),308.0,459.0,BUL,ITA
Group B,1986.0,07 Jun 1986 - 12:00,Group B,Estadio Azteca,Mexico City,Mexico,1.0,1.0,Paraguay,,114600.0,1.0,0.0,COURTNEY George (ENG),FREDRIKSSON Erik (SWE),IGNA Ioan (ROU),308.0,680.0,MEX,PAR
Group C,1998.0,18 Jun 1998 - 21:00,Group C,Stade de France,Saint-Denis,France,4.0,0.0,Saudi Arabia,,80000.0,1.0,0.0,BRIZIO CARTER Arturo (MEX),SALINAS Reynaldo (HON),TORRES ZUNIGA Luis (CRC),1014.0,8745.0,FRA,KSA
Group D,2010.0,23 Jun 2010 - 20:30,Group D,Soccer City Stadium,Johannesburg,Ghana,0.0,1.0,Germany,,83391.0,0.0,0.0,SIMON Carlos (BRA),HAUSMANN Altemir (BRA),BRAATZ Roberto (BRA),249722.0,300061468.0,GHA,GER
Group E,2010.0,14 Jun 2010 - 13:30,Group E,Soccer City Stadium,Johannesburg,Netherlands,2.0,0.0,Denmark,,83465.0,0.0,0.0,St�phane LANNOY (FRA),DANSAULT Eric (FRA),UGO Laurent (FRA),249722.0,300061478.0,NED,DEN
Group F,1994.0,25 Jun 1994 - 12:30,Group F,Giants Stadium,New York/New Jersey,Saudi Arabia,2.0,1.0,Morocco,,76322.0,2.0,1.0,DON Philip (ENG),PEARSON Roy (ENG),YLI-KARRO Tapio (FIN),337.0,3070.0,KSA,MAR
Group G,2010.0,20 Jun 2010 - 20:30,Group G,Soccer City Stadium,Johannesburg,Brazil,3.0,1.0,C�te d'Ivoire,,84455.0,1.0,0.0,St�phane LANNOY (FRA),DANSAULT Eric (FRA),UGO Laurent (FRA),249722.0,300061488.0,BRA,CIV
Group H,2014.0,22 Jun 2014 - 13:00,Group H,Estadio do Maracana,Rio De Janeiro,Belgium,1.0,0.0,Russia,,73819.0,0.0,0.0,BRYCH Felix (GER),BORSCH Mark (GER),LUPP Stefan (GER),255931.0,300186481.0,BEL,RUS
Match for third place,1970.0,20 Jun 1970 - 16:00,Match for third place,Estadio Azteca,Mexico City,Germany FR,1.0,0.0,Uruguay,,104403.0,1.0,0.0,SBARDELLA Antonio (ITA),MARSCHALL Ferdinand (AUT),AGUILAR ELIZALDE Abel (MEX),3477.0,1843.0,FRG,URU
Play-off for third place,2014.0,12 Jul 2014 - 17:00,Play-off for third place,Estadio Nacional,Brasilia,Brazil,0.0,3.0,Netherlands,,68034.0,0.0,2.0,HAIMOUDI Djamel (ALG),ACHIK Redouane (MAR),ETCHIALI Abdelhak (ALG),255957.0,300186502.0,BRA,NED
Preliminary round,1934.0,27 May 1934 - 16:30,Preliminary round,San Siro,Milan,Switzerland,3.0,2.0,Netherlands,,33000.0,2.0,1.0,EKLIND Ivan (SWE),BERANEK Alois (AUT),BONIVENTO Ferruccio (ITA),204.0,1133.0,SUI,NED
Quarter-finals,1986.0,22 Jun 1986 - 12:00,Quarter-finals,Estadio Azteca,Mexico City,Argentina,2.0,1.0,England,,114580.0,0.0,0.0,BENNACEUR Ali (TUN),ULLOA MORERA Berny (CRC),DOTCHEV Bogdan (BUL),714.0,392.0,ARG,ENG
Round of 16,1986.0,15 Jun 1986 - 12:00,Round of 16,Estadio Azteca,Mexico City,Mexico,2.0,0.0,Bulgaria,,114580.0,1.0,0.0,ARPPI FILHO Romualdo (BRA),MENDEZ MOLINA Romulo (GUA),IGNA Ioan (ROU),309.0,463.0,MEX,BUL
Semi-finals,1986.0,25 Jun 1986 - 16:00,Semi-finals,Estadio Azteca,Mexico City,Argentina,2.0,0.0,Belgium,,114500.0,0.0,0.0,MARQUEZ RAMIREZ Antonio (MEX),MENDEZ MOLINA Romulo (GUA),SILVA VALENTE Carlos Alberto (POR),3469.0,388.0,ARG,BEL
Third place,2002.0,29 Jun 2002 - 20:00,Third place,Daegu World Cup Stadium,Daegu,Korea Republic,2.0,3.0,Turkey,,63483.0,1.0,3.0,MANE Saad (KUW),ALTRAIFI Ali (KSA),VERGARA Hector (CAN),43950500.0,43950063.0,KOR,TUR

In [18]:
# Média de publico por estádio
df2[['Publico','Estádio']].groupby(['Estádio']).mean()

                       Publico
Estádio
Arena Amazonia    40056.750000
Arena Fonte Nova  50385.000000
Arena Pantanal    39679.250000
Arena Pernambuco  41020.666667
Arena da Baixada  39247.750000
...                        ...
Wankdorf Stadium  38900.000000
Wembley Stadium   86448.222222
Westfalenstadion  46925.000000
White City        45662.000000
Zentralstadion    42000.000000

[181 rows x 1 columns]

In [19]:
df2[['Publico', 'Estádio']].groupby('Estádio').mean()

                       Publico
Estádio
Arena Amazonia    40056.750000
Arena Fonte Nova  50385.000000
Arena Pantanal    39679.250000
Arena Pernambuco  41020.666667
Arena da Baixada  39247.750000
...                        ...
Wankdorf Stadium  38900.000000
Wembley Stadium   86448.222222
Westfalenstadion  46925.000000
White City        45662.000000
Zentralstadion    42000.000000

[181 rows x 1 columns]